### ISSUE TITLE
Automatically Update Quick Search Every General/Midterm Election

### ISSUE THREAD

**Issue by funkybunch** [ncopenpass/CampaignFinance#118]
Let's see if we can get this to update automatically each election cycle.

Related to #117 

https://github.com/ncopenpass/CampaignFinance/pull/117/files/1b7b61ff9f3f7fd55a301bb20afa5b58b8c00944#diff-c7f7ca7fe2dbf105ab8e40b52edfeef7
https://github.com/ncopenpass/CampaignFinance/pull/117/files/1b7b61ff9f3f7fd55a301bb20afa5b58b8c00944?file-filters%5B%5D=.json#diff-1e59ef1dff0798c9c46bcc3f5925a3e5

**Comment by funkybunch** [comment]
Removing this from the MVP Project board - this can wait until post-MVP.

**Comment by mcelestini** [comment]
@funkybunch Going to close this now since a conversation in the slack describes this as something we don't want, in case we don't have data for the next election cycle yet
https://open-nc.slack.com/archives/C013RDNSH0C/p1598566529012700

I've extracted the year to a constant so that all we need to do is update it in one place and all UI/API routes will accept the change
