### ISSUE TITLE
Add placeholder text to search bar

### ISSUE THREAD

**Issue by SchaeStewart** [ncopenpass/CampaignFinance#88]
Currently the search only supports searching for Candidate by name, or contributors by name. We should add a placeholder text to the search bar explaining this

**Comment by Dafondo** [comment]
Looks like the `placeholder` prop isn't getting passed to the `input` child element of the `Search` component. Would like another pair of eyes on this before I open an issue in `trussworks/react-uswds`.

Currently we can do a dirty workaround by passing an `inputId` and manually setting a placeholder for the `input` element on page load.

**Comment by funkybunch** [comment]
Looks like the location the prop would need to be added is SUPER nested since its all compiled.

I think we should open up an issue.  Line 69 in https://github.com/trussworks/react-uswds/blob/main/src/components/Search/Search.tsx is where it would need to be added.

Alternatively, we could add the HTML that it renders to the `<Search>` component in the short term and add the `placeholder` attribute manually.

**Comment by SchaeStewart** [comment]
I can open an issue if you'd like. It looks like a pretty easy fix on their end so I can submit a PR for it once an issue is created. @Dafondo

**Comment by SchaeStewart** [comment]
I went ahead and opened the issue: https://github.com/trussworks/react-uswds/issues/403

**Comment by SchaeStewart** [comment]
And I submitted a pr: https://github.com/trussworks/react-uswds/pull/404

**Comment by funkybunch** [comment]
@SchaeStewart Sweet!  Hopefully they turn it around quickly.

**Comment by SchaeStewart** [comment]
Looks like it's released, we just need to upgrade our `usdws` version to `1.9.1`
https://github.com/trussworks/react-uswds/releases/tag/1.9.1
